### ISSUE TITLE
Windows: Include repositories from WSL 

### ISSUE THREAD

**Issue by MrLuje** [mohitsinghs/vscode-repo#2]
I am using vscode on windows 10 but mainly using WSL2 so 90% of my repositories are in WSL.
By default, the extension shows windows' repository but not the WSL ones, but is would be nice to display both windows & WSL repositories.

Workaround :
* go to %userprofile%\\.vscode\extensions\mohitsingh.repo-0.2.2-win32-x64\bin
* run `repo.exe init`
* edit `%APPDATA%\repo.yml` and add the following
```yaml
roots: 
  # host paths
  - path: c:\users\xxxxx  # put your home directory here
  # wsl paths
  - path: \\wsl$\YOUR_WSL_DISTRIB_NAME\home\YOUR_USERNAME\
```
* now it should properly show both windows & wsl repositories
